// pos/src/components/InstallPwaButton.tsx
import React, { useEffect, useState } from 'react';
import { Download } from 'lucide-react';

interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>;
}

const isStandalone = () =>
  (typeof window.matchMedia === 'function' && window.matchMedia('(display-mode: standalone)').matches) ||
  Boolean((window.navigator as Navigator & { standalone?: boolean }).standalone);

export const InstallPwaButton: React.FC = () => {
  const [prompt, setPrompt] = useState<BeforeInstallPromptEvent | null>(null);
  const [installed, setInstalled] = useState(isStandalone);
  const isIos = /iphone|ipad|ipod/i.test(window.navigator.userAgent);

  useEffect(() => {
    const capturePrompt = (event: Event) => {
      event.preventDefault();
      setPrompt(event as BeforeInstallPromptEvent);
    };
    const markInstalled = () => {
      setInstalled(true);
      setPrompt(null);
    };

    window.addEventListener('beforeinstallprompt', capturePrompt);
    window.addEventListener('appinstalled', markInstalled);
    return () => {
      window.removeEventListener('beforeinstallprompt', capturePrompt);
      window.removeEventListener('appinstalled', markInstalled);
    };
  }, []);

  if (installed || (!prompt && !isIos)) return null;

  const install = async () => {
    if (!prompt) {
      window.alert('บน iPhone/iPad ให้แตะปุ่มแชร์ใน Safari แล้วเลือก “เพิ่มไปยังหน้าจอโฮม”');
      return;
    }
    await prompt.prompt();
    await prompt.userChoice;
    setPrompt(null);
  };

  return (
    <button
      id="nav-install-pwa-btn"
      onClick={install}
      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl bg-red-50 dark:bg-red-500/10 hover:bg-red-100 dark:hover:bg-red-500/20 border border-red-200 dark:border-red-500/30 text-red-700 dark:text-red-300 text-xs font-bold transition-all"
      title="ติดตั้ง LiveMatch POS บนอุปกรณ์นี้"
      type="button"
    >
      <Download className="w-4 h-4" />
      <span className="hidden lg:inline">ติดตั้งแอป</span>
    </button>
  );
};

// frontend/src/components/InstallPwaButton.vue
<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { Download } from '@lucide/vue'

const deferredPrompt = ref(null)
const installed = ref(false)
const isIos = /iphone|ipad|ipod/i.test(navigator.userAgent)

const isStandalone = () =>
  (typeof window.matchMedia === 'function' && window.matchMedia('(display-mode: standalone)').matches) ||
  window.navigator.standalone === true
const visible = computed(() => !installed.value && !isStandalone() && (Boolean(deferredPrompt.value) || isIos))

function capturePrompt(event) {
  event.preventDefault()
  deferredPrompt.value = event
}

function markInstalled() {
  installed.value = true
  deferredPrompt.value = null
}

async function install() {
  if (!deferredPrompt.value) {
    window.alert('บน iPhone/iPad ให้แตะปุ่มแชร์ใน Safari แล้วเลือก “เพิ่มไปยังหน้าจอโฮม”')
    return
  }

  deferredPrompt.value.prompt()
  await deferredPrompt.value.userChoice
  deferredPrompt.value = null
}

onMounted(() => {
  installed.value = isStandalone()
  window.addEventListener('beforeinstallprompt', capturePrompt)
  window.addEventListener('appinstalled', markInstalled)
})

onUnmounted(() => {
  window.removeEventListener('beforeinstallprompt', capturePrompt)
  window.removeEventListener('appinstalled', markInstalled)
})
</script>

<template>
  <button
    v-if="visible"
    class="inline-flex h-9 items-center gap-1.5 rounded-xl border border-court-200 bg-white px-2.5 text-xs font-black text-court-700 transition hover:bg-court-500/10 dark:border-court-900 dark:bg-stone-800 dark:text-court-300 sm:h-10 sm:px-3"
    type="button"
    title="ติดตั้ง LiveMatch บนอุปกรณ์นี้"
    @click="install"
  >
    <Download class="h-4 w-4" />
    <span class="hidden sm:inline">ติดตั้งแอป</span>
  </button>
</template>
